# Generated by Django 5.1.4 on 2025-01-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitbodypart",
            name="url_path",
            field=models.URLField(default=""),
        ),
    ]
