# Generated by Django 5.1.4 on 2025-01-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="is_patient_present",
            field=models.BooleanField(blank=True),
        ),
    ]
