# Generated by Django 5.1.4 on 2025-01-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_visit_is_patient_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("started", "Started"),
                    ("finished", "Finished"),
                    ("canceled", "Canceled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
