# Generated by Django 5.1.4 on 2025-01-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_visitbodypart_url_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="heure",
            field=models.TimeField(default="12:00"),
        ),
        migrations.AlterField(
            model_name="visit",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
