# Generated by Django 5.1.4 on 2025-01-09 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_visit_heure_alter_visit_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="heure",
        ),
    ]
