# Generated by Django 5.1.4 on 2025-05-10 16:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('peanuts', 'Peanuts'), ('dairy', 'Dairy'), ('gluten', 'Gluten'), ('shellfish', 'Shellfish'), ('soy', 'Soy'), ('eggs', 'Eggs'), ('tree_nuts', 'Tree Nuts'), ('wheat', 'Wheat'), ('fish', 'Fish'), ('sesame', 'Sesame')], default=None, max_length=200),
        ),
    ]
