# Generated by Django 5.1.4 on 2025-05-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patient_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitbodypart',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_path',
            field=models.TextField(unique=True),
        ),
    ]
