# Generated by Django 5.1.4 on 2025-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_visitbodypart_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitbodypart',
            name='distance_from_subjet',
            field=models.FloatField(null=True),
        ),
    ]
