# Generated by Django 5.1.4 on 2025-05-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_visitbodypart_distance_from_subjet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitbodypart',
            old_name='distance_from_subjet',
            new_name='distance_from_subject',
        ),
    ]
