# Generated by Django 5.1.4 on 2025-05-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_visitbodypart_annotations_visitbodypart_image_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitbodypart",
            name="distance_from_subject",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
