# Generated by Django 5.1.4 on 2025-05-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_visitbodypart_pixel_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitbodypart",
            name="image_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
