# Generated by Django 5.1.4 on 2025-05-16 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_visitbodypart_image_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitbodypart",
            name="comment",
        ),
    ]
