# Generated by Django 5.1.4 on 2025-05-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_visitbodypart_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitbodypart",
            name="image_path",
            field=models.ImageField(unique=True, upload_to=""),
        ),
    ]
