# Generated by Django 5.1.4 on 2025-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_visitbodypart_image_preview_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitbodypart",
            name="image_preview_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="visitbodypart",
            name="image_preview_width",
            field=models.IntegerField(default=0),
        ),
    ]
