# Generated by Django 5.1.4 on 2025-05-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_visitbodypart_image_preview_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitbodypart",
            name="image_preview_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
