# Generated by Django 5.1.4 on 2025-05-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_visitbodypart_image_preview_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitbodypart",
            name="image_preview_path",
            field=models.ImageField(unique=False, upload_to=""),
        ),
    ]
