# Generated by Django 5.1.4 on 2025-05-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_visitbodypart_image_preview_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitbodypart",
            name="image_preview_path",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
