# Generated by Django 5.1.4 on 2025-05-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_visitbodypart_image_preview_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitbodypart",
            name="focal",
            field=models.FloatField(default=3.543),
        ),
    ]
