# Generated by Django 5.1.4 on 2025-05-17 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_visitbodypart_focal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitbodypart",
            name="annotations",
        ),
    ]
