# Generated by Django 5.1.4 on 2025-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_visitbodypart_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitbodypart",
            name="annotations",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
