# Generated by Django 5.1.4 on 2025-05-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_visitbodypart_annotations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitbodypart",
            name="annotations",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
