# Generated by Django 5.1.4 on 2025-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_visitbodypart_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitbodypart',
            name='image_super_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitbodypart',
            name='image_super_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitbodypart',
            name='image_super_path',
            field=models.ImageField(default='', unique=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visitbodypart',
            name='image_super_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitbodypart',
            name='multi_image_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_preview_path',
            field=models.ImageField(default='', unique=True, upload_to=''),
        ),
    ]
