# Generated by Django 5.1.4 on 2025-05-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_visitbodypart_image_super_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_super_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
