# Generated by Django 5.1.4 on 2025-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_visitbodypart_image_super_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_preview_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_preview_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
