# Generated by Django 5.1.4 on 2025-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_visitbodypart_image_super_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitbodypart',
            name='multi_image_path',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
