# Generated by Django 5.1.4 on 2025-06-09 08:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_patient_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_preview_path',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_preview_path),
        ),
    ]
