# Generated by Django 5.1.4 on 2025-06-09 09:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_visitbodypart_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitbodypart',
            name='image_super_path',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_super_path),
        ),
    ]
