# Generated by Django 5.1.4 on 2025-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="id",
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="INAMI",
            field=models.CharField(max_length=255),
        ),
    ]
