# Generated by Django 5.1.4 on 2025-01-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "INAMI",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                ("city", models.CharField(max_length=255)),
                ("zip_code", models.IntegerField()),
                ("phone_number", models.CharField(max_length=255)),
                ("other_phone_number", models.CharField(max_length=255)),
                ("is_retired", models.BooleanField()),
            ],
        ),
    ]
